### ISSUE TITLE
Numeric primary key column can't handle zeroes.

### ISSUE THREAD

**Issue by Sanitator** [DataTables/Editor-Node#1]
Hi, first off, thanks for the great plugin! The documentation's great, and I got set up with a working webpage for trying out Editor couple days into my trial. There's been some issues, but mostly nothing I couldn't work around. 

One thing that kept recurring though was that if I have an SQL table with a primary key column of Decimal type, Editor can't seem to handle it. The change goes through to the back-end, but then Editor throws an error, row 342 in editor.js, 'Primary key element is not available in the data set'. The table is unusable by Editors front-end after this, it fails to load every time until I go remove the offending value.

Looking at the code, there's this null check which seems to discard the valid zero values a few rows above that previously mentioned row: 

```
            if (flat) {
                val = row[column] ?
                    row[column] :
                    null;
            }
```

I can probably make quick fixes for my own setup here, but the handling here needs improvement. Maybe add another branch for extended handling if the primary key column is any number-type?

**Comment by DataTables** [comment]
Thanks for this. I hadn't expected the primary key to be a `0`. Typically I've seen it as can auto increment / sequence / serial (whatever) value, starting at 1 and increasing, or a uuid string, etc.

Are you allowing the primary key value to be entered, or do you have a sequence which starts at 0? Either way, I agree, that code should be improved.

**Comment by Sanitator** [comment]
Thanks for the quick reply!

In this case I had a MySQL table set up with three columns, of which two
are meant to be limits for product dimensions. Couple rows had lower bounds
undefined, so the minimum value was set as a zero. This first prevented
displaying the table with editor at all, but I could work around that by
either removing the rows, or changing the values to some other dummy
values.

What bothered me was the idea that end-users could potentially break my
editing view if they were to try and change the value for these min-max
values to zero for any reason, the whole table gets nuked if that happened.

My quick fix for this issue was this

if (row[column] == 0) val = 0;

added after the previous null check. It seemed to fix the issue, but I
haven't done that much testing yet, and there might be some other values
the previous check was invalidating, dont know.

Sami

**Comment by Sanitator** [comment]
Oh, whoops, meant to say with three primary key columns. So yes, compound key.
