### ISSUE TITLE
Upload file response "No data detected. Have you used `{extended: true}` for `bodyParser`?"

### ISSUE THREAD

**Issue by clarencetw** [DataTables/Editor-Node#2]
I use this datatables.net-editor-demo@1.7.4 sample to test "File upload" I get "No data detected. Have you used `{extended: true}` for `bodyParser`?"
But I use datatables.net-editor-demo@1.7.3 test "File upload" is success.
It's may have bug?

**Comment by DataTables** [comment]
It appears to work for me locally. Can you show me your client-side and server-side code please?

**Comment by clarencetw** [comment]
This is my code https://drive.google.com/file/d/14bnqKh5BQkFSiUN_WGp8GXKwb7siiUGX/view?usp=sharing
And this my screenshot
![Alt text](https://i.imgur.com/SXVOmHm.png)

**Comment by DataTables** [comment]
Apologies - I've not had a chance to look into this today. I will do so tomorrow!

**Comment by DataTables** [comment]
You are absolutely right - sorry about that. Fix committed now :).

**Comment by clarencetw** [comment]
@DataTables Sorry, I use sample https://editor.datatables.net/download/download?type=nodejs to download and use npm install today?
Then I see
![2018-09-12 12 01 51](https://user-images.githubusercontent.com/5698291/45401552-b21cc100-b683-11e8-993e-43d82713ffa8.png)

I use version is 1.7.4

**Comment by DataTables** [comment]
This isn't in a release version of Editor yet I'm afraid. You'd need to use the master version from github directly rather than 1.7.4 from npm. Alternatively, I'm working on 1.8 at the moment and that will be available soon with the fix.
