### ISSUE TITLE
Vulnerability knex <2.4.0

### ISSUE THREAD

**Issue by tutyamxx** [DataTables/Editor-Node#28]
https://github.com/advisories/GHSA-4jv9-3563-23j3

```
node_modules/datatables.net-editor-server/node_modules/knex
node_modules/knex
  datatables.net-editor-server  *
  Depends on vulnerable versions of knex
  node_modules/datatables.net-editor-server
```

**Comment by AllanJard** [comment]
Hi - [fix was committed here](https://github.com/DataTables/Editor-Node/commit/1903f7af6180becd6ed3961ae923f402c0bd55dc). I'm working on other updates at the moment and will tag a release soon.

**Comment by tutyamxx** [comment]
Thank you kindly.
